server:
  port : 8082
  servlet:
    context-path: /api/${parcom.api.version}


parcom:
  kafka:
    bootstrap-address: pc-kafka:9092
    topic:
      notification: notification
  api:
    version: v1

spring:
  application.name: pc-news
  hateoas:
    use-hal-as-default-json-media-type: false
  data:
    mongodb:
      uri: mongodb://pc-news-mongo/parcom
management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: "health,prometheus"
  metrics:
    tags:
      application: ${spring:application:name}
